//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyectoflores.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloques.
        /// </summary>
        public static string _Layout_Bloques {
            get {
                return ResourceManager.GetString("_Layout_Bloques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fertirriego.
        /// </summary>
        public static string _Layout_Fertirriego {
            get {
                return ResourceManager.GetString("_Layout_Fertirriego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fincas.
        /// </summary>
        public static string _Layout_Fincas {
            get {
                return ResourceManager.GetString("_Layout_Fincas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Índice.
        /// </summary>
        public static string _Layout_inicio {
            get {
                return ResourceManager.GetString("_Layout_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invernaderos.
        /// </summary>
        public static string _Layout_Invernaderos {
            get {
                return ResourceManager.GetString("_Layout_Invernaderos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción.
        /// </summary>
        public static string _Layout_Produccion {
            get {
                return ResourceManager.GetString("_Layout_Produccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string _Layout_Usuarios {
            get {
                return ResourceManager.GetString("_Layout_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string Finca_Lista_ciudad {
            get {
                return ResourceManager.GetString("Finca_Lista_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Finca_Lista_Id {
            get {
                return ResourceManager.GetString("Finca_Lista_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre finca.
        /// </summary>
        public static string Finca_Lista_nombre {
            get {
                return ResourceManager.GetString("Finca_Lista_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento .
        /// </summary>
        public static string Finca_Lista_region {
            get {
                return ResourceManager.GetString("Finca_Lista_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este sistema de inventario esta desarrollado único y exclusivamente para los
        ///propietarios y administradores de las empresas de flores, si usted por algún motivo
        ///logro acceder sin hacer parte de alguno de estos dos últimos a los cuales se hace
        ///referencia, por favor salga del sistema y no haga mal uso de esta aplicación web..
        /// </summary>
        public static string Home_parrafo {
            get {
                return ResourceManager.GetString("Home_parrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al sistema de información para la producción de flor..
        /// </summary>
        public static string Home_parrafo1 {
            get {
                return ResourceManager.GetString("Home_parrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE INFORMACIÓN PRODUCCIÓN DE FLOR.
        /// </summary>
        public static string Home_Titulo {
            get {
                return ResourceManager.GetString("Home_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acceder.
        /// </summary>
        public static string Login_boton_acceso {
            get {
                return ResourceManager.GetString("Login_boton_acceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Login_contraseña {
            get {
                return ResourceManager.GetString("Login_contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario.
        /// </summary>
        public static string Login_usuario {
            get {
                return ResourceManager.GetString("Login_usuario", resourceCulture);
            }
        }
    }
}
