//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectoflores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class invernadero
    {
        public int idinvernadero { get; set; }

        [Required]
        [Display(Name = "Numero de invernadero")]       
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public int numeroinvernadero { get; set; }
        [Required]
        [Display(Name = "Finca")]
        public int idfinca { get; set; }
    
        public virtual finca finca { get; set; }

        [NotMapped]
        public List<finca> FincaCollection { get; set; }
    }
}
