//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Proyectoflores.Models
{

    public partial class usuario
    {
        public int cedula { get; set; }
        public string password { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int idrol { get; set; }
        public int idfinca { get; set; }
    
        public virtual finca finca { get; set; }
        public virtual rol rol { get; set; }

        public List<finca> fincaCollection { get; set; }
        public List<rol> rolCollection { get; set; }
    }
}
